deployment:
  - changed-files:
      - any-glob-to-any-file: 
          - '.github/workflows/*.yml'
          - '!.github/workflows/labeler.yml'

design:
  - changed-files:
      - any-glob-to-any-file: 
          - '*.png'
          - '*.svg'
          - '*.jpg'
          - '*.css'

documentation:
  - changed-files:
      - any-glob-to-any-file: 
          - '*.md'
          - '*.pdf'
